### PR TITLE
Simplify the installation line

### PR DESCRIPTION
**Pull request by bugaevc**
- Why save and `chmod` the file if we can just pipe it to `sudo bash`?
- This also changes `su -c` to `sudo`, since I believe that setups that support `sudo` (i.e. the user is in sudoers) are more common than those that support bare `su` (i.e. the root password is set). Since the command is nice & short now, it would be trivial for the user to replace `sudo` with `su -c` for themselves if they want to.
- It seems like the page itself hasn't been updated with new stuff from this repo recently, can this be fixed?
- It's a bad bad idea to ask users to `curl http://... | sudo bash` (with or without saving the file). Getting HTTPS ASAP is a good idea.

### CODE REVIEW

**Comment by bugaevc** [comment]
This won't really work because `sudo` may require interactive input.

**Comment by satya164** [comment]
> Why save and chmod the file if we can just pipe it to sudo bash?

Last time I tried, it didn't work properly. Can't exactly remeber why

> This also changes su -c to sudo, since I believe that setups that support sudo (i.e. the user is in sudoers) are more common than those that support bare su (i.e. the root password is set). Since the command is nice & short now, it would be trivial for the user to replace sudo with su -c for themselves if they want to.

Fedora doesn't have `sudo` by default, unless you enable during installation (not sure if it has changed)

> It seems like the page itself hasn't been updated with new stuff from this repo recently, can this be fixed?

Please send a PR :)

> It's a bad bad idea to ask users to curl http://... | sudo bash (with or without saving the file). Getting HTTPS ASAP is a good idea.

Yeah, we need to get HTTPS. cc @Abhinav1217

**Comment by bugaevc** [comment]
> Last time I tried, it didn't work properly. Can't exactly remeber why

I guess it was because...

> This won't really work because sudo may require interactive input.

And I can't find a way to overcome this.

> Fedora doesn't have sudo by default, unless you enable during installation (not sure if it has changed). The one liner should work without changing for any kind of set up.

Not really, In the installer, there are two options: you can make your user an administrator (i.e. you'll be able to use `sudo`) and/or you can set the root password (i.e. you'll be able to use `su`). IIUC, neither is enabled by default. But I _believe_ most people use `sudo`.

How about `su -c "curl ... | bash"`?

>> It seems like the page itself hasn't been updated with new stuff from this repo recently, can this be fixed?

> Please send a PR :)

Uh, I mean you should log in to the server and update the content it's serving from this very repo. Not sure how could I do that with a PR.

Also, you really should release a new version of Fedy itself. F24 has been out for a long time and the Arc theme still can't be installed (fixed in master).

**Comment by satya164** [comment]
> How about su -c "curl ... | bash"?

Sure, I'm not on a Fedora machine right now, so can't test.

> Uh, I mean you should log in to the server and update the content it's serving from this very repo. Not sure how could I do that with a PR.

Ah. Got it.

> Also, you really should release a new version of Fedy itself. F24 has been out for a long time and the Arc theme still can't be installed (fixed in master).

I don't manage the releases any more. Hope @Abhinav1217 will release a new version soon.

**Comment by bugaevc** [comment]
> It's a bad bad idea to ask users to curl http://... | sudo bash (with or without saving the file). Getting HTTPS ASAP is a good idea.

Alternatively, you could just use GitHub as a HTTPS hosting: `curl https://raw.githubusercontent.com/folkswithhats/folkswithhats.org/master/fedy-installer`. That would just be `curl https://git.io/vKyld` if shortened, still via HTTPS.

**Comment by bugaevc** [comment]
Not to spam you, but another great option would be to use GitHub pages as a hosting for the whole site. It would automatically get you HTTPS and auto-updates from this repo.

You can use it with the custom domain as well: https://help.github.com/articles/using-a-custom-domain-with-github-pages/

**Comment by satya164** [comment]
> @bugaevc Not to spam you, but another great option would be to use GitHub pages as a hosting for the whole site. It would automatically get you HTTPS and auto-updates from this repo.

We used to do that. The problem with that is we can't have subdomains hosted somewhere else while having the main site on Github pages. We want to have the repo in a subdomain, so we had to choose a custom hosting solution.

We can use [letsencrypt.org] for HTTPS. Someone just needs to do it.

**Pull request closed without merging**
